seed: 6
custom_save: agree_d2_s6
checkpoint:

dataset:
  name: FashionMNIST
  root: .data
  apply_manipulation:
  ind_to_keep:
  binary_class:
  color:
  how:
  r:

dataloader:
  batch_size: 100
  num_workers: 2
  shuffle: True
  valid_ratio: 0.2
  subset: False

model:
  fn: networks.nets
  name: CCP_non_poly
  args:
    n_degree: 2
    hidden_size: 16

training_info:
  epochs: 25
  display_interval: 200
  lr: .001
  save_every_epoch: 50
  test_every_epoch: 1
  weight_dec: 0
