seed: 0
custom_save: ensemble_mid2
checkpoint:

dataset:
  name: CIFAR100
  root: ./.data
  apply_manipulation:
  ind_to_keep:
  binary_class:
  color:

dataloader:
  batch_size: 128
  num_workers: 2
  shuffle: True
  valid_ratio: 0.2
  subset: False

model:
  fn: networks.resnet_pi_min
  name: NCPS
  args:
    train: True
    use_activ: False
    use_alpha: True
    n_lconvs: 1
    norm_local: 1
    num_blocks: [2, 2, 1, 1]
    norm_x: -1
    n_xconvs: 0

training_info:
  lr: 0.1
  epochs: 40
  save_every_epoch: 60
  test_every_epoch: 1
  display_interval: 200

lr_scheduler: MultiStepLR
learning_rate:
  milestones: [15, 25, 35, 45]
  gamma: 0.1

