seed: 0
custom_save: ensemble_low_cosine
checkpoint:

dataset:
  name: CIFAR100
  root: ./.data
  apply_manipulation:
  ind_to_keep:
  binary_class:
  color:

dataloader:
  batch_size: 128
  num_workers: 2
  shuffle: True
  valid_ratio: 0.2
  subset: False

model:
  fn: networks.resnet_pi_min
  name: NCPS
  args:
    train: True
    use_activ: False
    use_alpha: True
    n_lconvs: 1
    norm_local: 1
    num_blocks: [1, 1, 1, 1]
    n_channels: [32, 64, 128, 128]
    norm_x: -1
    n_xconvs: 0

training_info:
  lr: 0.2
  epochs: 50
  save_every_epoch: 100
  test_every_epoch: 1
  display_interval: 200

lr_scheduler: CosineAnnealingWarmRestarts
learning_rate:
  T_0: 50
