seed: 0
custom_save: poly4_64.32.16.8_avgpool_nodrop
checkpoint:

dataset:
  name: CIFAR10
  root: .data
  apply_manipulation:
  ind_to_keep:
  binary_class:
  color:
  how:
  r:

dataloader:
  batch_size: 100
  num_workers: 2
  shuffle: True
  valid_ratio: 0.2
  subset: False

model:
  fn: networks.nets
  name: CCP_4
  args:
    n_degree: 4
    hidden_size: 16

training_info:
  epochs: 100
  display_interval: 200
  lr: .0001
  save_every_epoch: 50
  test_every_epoch: 5
  weight_dec: 0

lr_scheduler: MultiStepLR
learning_rate:
  milestones: [40, 60, 80, 100]
  gamma: 0.1