seed: 0
custom_save: test
checkpoint:


dataset:
  name: CIFAR10
  root: data
  apply_manipulation:
  ind_to_keep:
  binary_class:
  color:

dataloader:
  batch_size: 64
  num_workers: 2
  shuffle: True
  valid_ratio: 0.2
  subset: True

model:
  fn: networks.nets
  name: CCP
  args:
    n_degree: 2
    hidden_size: 16

training_info:
  epochs: 80
  display_interval: 10
  lr: .001
  save_every_epoch: 40
  test_every_epoch: 5