seed: 0
custom_save: test
checkpoint:

dataset:
  name: CIFAR10
  root: data
  apply_manipulation:
  ind_to_keep:
  binary_class:
  color:

dataloader:
  batch_size: 64
  num_workers: 2
  shuffle: True
  valid_ratio: 0.2
  subset: True

model:
  fn: networks.resnet
  name: ResNetnew
  args:
    train: True
    num_blocks: [1, 1, 1, 1]
    n_channels: [32, 64, 128, 128]

training_info:
  lr: 0.1
  lr_milestones: [40, 60, 80, 100]
  lr_gamma: 0.1
  epochs: 10  # this is total, so if we load a checkpoint with 40, will only do 40 epochs
  save_every_epoch: 5
  test_every_epoch: 5
  display_interval: 10